### ISSUE TITLE
[Feature request] Adding errata text on components

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#1]
Would it be possible to put some text on cards noting errata text? A few of them are game-chaging like for Fractured Reality or Lost Knowledge.

On that note, while the internal PDF viewer doesn't have any annotation or comment capacity and so you can't do anything about rule errata, how about editing the source PDF file themselves? I've just tried dumping the EH Reference Guide downloaded from FFG to https://www.sejda.com and edited a few text, the exported result looks quite alright. Putting fixed versions alongside the original ones in the game would be great for people like me who didn't mind altered components from the board game version if they help smoothen the gameplay.

**Comment by snebjorn** [comment]
Unfortunately TTP doesn't support description on cards in a deck. I asked for a feature to put a description via a tooltip on cards but it was denied as it must work for VR as well.

I also contacted Fantasy Flight Games for an updated PDF and cards but they've not answered - so far. I wrote them a long time ago.

I have edited cards and PDFs before but it takes a long time. Now that I'm done with importing and fixing all the cards I can tinker more :)

Do you a list of the things that need fixing? I'll take a look.
You're also welcome to edit stuff and send a "change suggestion" via the "Pull Request" system :)

**Comment by snebjorn** [comment]
Each PDF is in the Textures folder in their respective expansion subfolder.
So the Errata PDF is located here: [src/Textures/01 Core/eh_errata__faq_2017-08-11.pdf](https://github.com/snebjorn/ttp-eldritch-horror/blob/master/src/Textures/01%20Core/eh_errata__faq_2017-08-11.pdf) and the rulebook PDF for Forsaken Lore is here [src/Textures/02 Forsaken Lore/eh02_rulebook.pdf](https://github.com/snebjorn/ttp-eldritch-horror/blob/master/src/Textures/02%20Forsaken%20Lore/eh02_rulebook.pdf), etc...

**Comment by snebjorn** [comment]
I've tried various PDF editors and editing them is painful. Something is broken in all the editors I've tried.
It might be possible to get an acceptable result if I edit the individuel bits that work in each editor. But oh man I need to be real bored to attempt that :)

I wrote Fantasy Flight Games for updated PDFs - again
Lets see what happens

**Comment by metapone** [comment]
I got as far as getting all the fonts used inside the PDFs, but couldn't get it right blurring the new text to match the opacity of the old PDF text. They stood out like a sore thumb so I gave up too. Someone on BoardGameGeek make a composite PDF for all the expansion with the updated errata so I thought I could use that, but one, it's not updated to the latest expansion and two, he tried his best but the result still look noticably worse than the original PDF. I ended up using annotations to mark the PDFs outside of the game and just Alt-Tab whenever I want to read it; my PDF viewer is better than the in-game one anyway.

It has been a week since I first sent a ticket to FFG, so it looks like they ain't gonna budge. Oh well.

**Comment by metapone** [comment]
In case you miss my edit way earlier:

> is it possible to add a mark as a reference on the cards that needs errata? Like a tiny red square on a card corner to remind players to check the errata file.

Have you tried this idea yet? If you did and it's not possible, I think this issue can be closed then. Seems like nothing feasible could be done about the errata, and FFG doesn't even email me back about the my status update request.

**Comment by metapone** [comment]
> is it possible to add a mark as a reference on the cards that needs errata? Like a tiny red square on a card corner _(or a "!" text)_ to remind players to check the errata file

@snebjorn sorry for asking again, but could you add this feature in the near future if possible?

**Comment by metapone** [comment]
Just knowing it is possible and you would probably get to it in the future is enough for me 👯‍♂️

**Comment by snebjorn** [comment]
I added an Elder sign to everything that was altered by the Errata.

Example:
![](https://github.com/snebjorn/ttp-eldritch-horror/blob/master/assets/01%20Core/Assets/Dynamite%20-%20Errata.png?raw=true)

![](https://github.com/snebjorn/ttp-eldritch-horror/blob/master/assets/01%20Core/Ancient%20Ones/Shub-Niggurath/Shub-Niggurath%20-%20Errata%20-%20back.png?raw=true)

**Comment by metapone** [comment]
That's actually way cooler than what I had in mind.
