### ISSUE TITLE
Spawned Monsters and tokens sometimes go under Gates

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#10]
When spawning a Gate sometimes the Monster would be put below it instead of above it. Same with spawning Clues, they would slide below it.

**Comment by snebjorn** [comment]
I've noticed this as well. I believe it's the TTP collision engine just doing random things - it tends to do that.
I plan on re-visiting this when [Stack Anything](https://trello.com/c/vGjjRxSL/56-stack-anything) is implemented in TTP
