### ISSUE TITLE
[Feature Request] Search Personal Stories by Investigator name

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#11]
I think allowing players to search by Investigator name is more useful than by Stories name for new players who couldn't remember the Story name of each Investigator yet.

**Comment by snebjorn** [comment]
Players shouldn't need to find their Personal Story themselves. It's fetched when they setup their Investigator.

What that not working?

**Comment by metapone** [comment]
It didn't, but now I can't reproduce it with a new game. Closing in for now.

This is the 2nd time an unreproducable error happened to me. In the future I'll try to remember to reproduce them first before opening a ticket like this. Sorry.

**Comment by snebjorn** [comment]
If the Personal Story isn't fetched during setup. Must likely there's a typo somewhere. Please report the Investigator and I'll can get it fixed in a jiffy

**Comment by metapone** [comment]
No, must be something on my end because it happened to both of my Investigators. I've just try a new game and they both have their Story fetched without any problem.
