### ISSUE TITLE
Add unused Rumor Mythos cards to the table after starting a game

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#12]
There's a Mythos card named [The Storm](https://eldritchhorror.fandom.com/wiki/The_Storm) that requires resolving 1 Rumor Mythos card _from the game box._ A deck of unused Rumor Mythos card would be needed to handle this case.

**Comment by snebjorn** [comment]
Was unaware of this. I'll get it fixed.

Are you aware of any other cards that fetch stuff from the game box?

**Comment by metapone** [comment]
The EH wiki have all card data beside Encounters, so I'll give it a simple search and report back.

**Comment by metapone** [comment]
Seems there is only this other one: [Abandon Hope](https://eldritchhorror.fandom.com/wiki/Abandon_Hope):

> Draw 3 Yellow Mythos cards from the game box and resolve the text effect of each. Then discard these cards.

**Comment by metapone** [comment]
Oops, there're more:
[Evil of Old](https://eldritchhorror.fandom.com/wiki/Grand-mere%27s_Warning) (Same as Abandon Hope)
> When you gain this card, draw 3 yellow Mythos cards from the game box and resolve the text effect of each. Then discard those cards.

[Pact with Eibon](https://eldritchhorror.fandom.com/wiki/Dark_Pact)
> Shuffle one yellow and 1 green Mythos card from the game box into the Mythos deck. Then discard the top 3 cards of the Mythos Deck.
