### ISSUE TITLE
[Feature Request] Notify user or disable Mythos configuration when setting up game if not enough Mythos cards available

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#15]
If I only load the Mountains of Madness expansion and choose Only Easy Mythos, choosing any Ancient One will cause the components to load and shuffle underneath the setup page, but the page won't disappear and the user won't be able to start the game (correct per the rule). Either adding a visual indicator or disabling Mythos configuration would help the user to understand the error better.

**Comment by snebjorn** [comment]
I'll get that fixed
