### ISSUE TITLE
Cards aren't fetched when setting up investigators with a prelude

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#16]
If the Prelude "Aid of the Elder Gods" is used and Nyarlathotep isn't the Ancient One, when setting up the investigators the Clue will be fetched for each one but not the Corruption condition. Also worth mentioning is that at least an investigator, Calvin, would not be affected by this bug because he already starts with a Corruption card already and you can't get a duplicate condition. There may be other cases where an investigators start with a condition already, but I only know of Calvin.

**Comment by snebjorn** [comment]
Thanks for reporting. Fixed in next release.
