### ISSUE TITLE
Mythos deck's stages are reversed

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#19]
The 3rd stage's cards are on top instead of at the bottom. That partially explains why I can't seem to get any Rumor with Cthulhu and Azathoth.
Also, there doesn't seem to be any randomization? I've just check the Mythos for Cthulhu and they are in the exact order (in reverse) as listed in the AO sheet (so 3 green, 4 yellow, 1 green, 3 yellow, 2 yellow and finally 2 blue).

**Comment by snebjorn** [comment]
Good catch. I'll get it fixed!
