### ISSUE TITLE
[Feauture Request] Get random cards with a specific trait from deck

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#2]
Disclaimer: not my idea btw, it's the game dev's idea. Not sure how time saving it would be but kinda nice to have; just close this if you don't think it's worthwhile.

You know how certain cards like [Rally the People](https://eldritchhorror.fandom.com/wiki/Rally_the_People) has the effect "gains 1 random _card type_ from the deck"? You use the Stack Explorer, type the tag in (nice), get the 1st card on top according to the reference guide, drag it out, and finally shuffle the deck. If there are a way to do all that by using context menus or buttons it would be quite convenient.

![image](https://user-images.githubusercontent.com/52821877/164886353-e296118e-b2ce-4481-948f-f721a89e5513.png)

**Comment by snebjorn** [comment]
TTP got tag support in the latest update. Tag support was a long requested feature of mine :)

So now you can search decks by trait.

**Patch notes:**
- You can now find cards by their traits by using the stack explorer.
  - Example: right click the asset pile and type "tome", now all tomes will be shown.

Unfortunately TTP can only filter/search for 1 tag.

The rules state:
> **Gaining a Card with a Specific Trait**: Some effects instruct an
investigator to gain a card with a specific trait (for example, “Gain
a Madness Condition”). The investigator searches that card type’s
deck then discard pile for the first card matching the specified trait
and gains that card. Then he shuffles the deck.
> - An investigator that gains a Spell or Condition in this way
> searches the deck for the first card matching the specified trait
he does not already have and gains that card.

And remember decks with double sided cards are drawn from the bottom

**Comment by metapone** [comment]
I was thinking along the line of a button for each trait/type, like a Spell button, an Ally button etc. that will draw one card from the deck when I created this question. That said, when thinking deeper I realized that would be a lot of buttons. So yeah, not a great idea.

**Comment by snebjorn** [comment]
I was tinkering with the idea to add a right click custom action to cards that gave cards. So you could right click and "gain 1 weapon asset" if the card would grant a weapon asset.
But that's not currently feasible in TTP.
