### ISSUE TITLE
[Feature Request] Ping when Doom advances past 0 when advancing the Omen 

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#22]
Say there are 4 Red Gates in play and Doom is at 3. When the Omen advances to Red, the Doom token will move from 3 to 0, but if the players miscount the number of Gates they wouldn't realize they have to execute the Doom advance replacement effect 1 time after flipping the Ancient One. Since players normally rely on the mod to advance Doom and only switch to manually handle the effect after flipping the Ancient One, a ping on the token to remind the players there are still leftover effect would be good to help. A number showing the leftover Doom along with the ping would be even better, since the ping alone could be mistakenly thought of as just a reminder to flip the Ancient One.

**Comment by snebjorn** [comment]
I believe I write it in chat if the doom can't be moved the appropriate count

**Comment by metapone** [comment]
I see, thanks. That is the first time I've seen a function put in the chat window for this game. Are there any other functions like that?

**Comment by snebjorn** [comment]
> I see, thanks. That is the first time I've seen a function put in the chat window for this game. Are there any other functions like that?

Ye all my script actions should say what they did in the chat. This is so players can check what happend in text should they not have paid attention to the board
