### ISSUE TITLE
Wrong Mythos color

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#23]
In a game with Yig as the Ancient One, I've got the following Mythos cards for the first stage: Heart of Corruption (green), Collector's Gift (green), Fruit of Labor (yellow), and Arrests Made in Murder Case! (yellow). Yig should have 1 green, 2 yellow and 1 blue for the first stage, and I've tried a few other games with Yig having the correct setup, so my guess is that one of those 4 cards got marked with the wrong color.

**Comment by snebjorn** [comment]
Nicely spotted. Found and fixed
