### ISSUE TITLE
Move starting Ongoing Mythos cards to next to the Ancient One

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#26]
If a Prelude spawn a Rumor, the Rumor will be placed in the discard zone next to the Mythos deck. I'm not sure what the correct placement is, but would like it to be to the right of the Ancient One sheet since in each Reckoning they are to be resolved in succession and having it there would be faster to check.

**Comment by snebjorn** [comment]
This is on purpose. I didn't make any ongoing rumor snaps. Players can place these where they see fit.

**Comment by snebjorn** [comment]
It's sort of a discard pile. But it's just where the last drawn mythos card will preside. Same practice for the encounter decks.

I usually just move the rumor cards to the side, either immediately or when I draw the next one

**Comment by metapone** [comment]
So it's the same as what I do. Now that I think about it, putting the starting Rumor close to the Mythos deck means you can't miss it after setup, even if you forgot to check the Prelude. That makes a lot of sense.
