### ISSUE TITLE
Missing health token for monsters

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#3]
Can't seem to find them anywhere. Am I suppose to copy and paste an Investigator's health token manually?

**Comment by snebjorn** [comment]
Hmm yeah that part isn't super user friendly. Copying a health token will work. You can also use the **Object Library**. Right click somewhere and choose Object Library. Then just pull out a health token.

![image](https://user-images.githubusercontent.com/1266245/164895854-a65521a3-a424-4706-babc-30ef561cce85.png)

**Comment by metapone** [comment]
I didn't know the Object Library already has every in-game assets available; the Tutorial makes it seems like it is only used to move something on the table into it.
That said, since everything else in the game right now is stored in containers (even dice, which its container behaves weirdly btw because I couldn't put my dice back into it; ended up just throwing the surplus one across the virtual table) but only the health tokens must be copied by hand, adding a stack of health tokens available would be more consistent.

**Comment by snebjorn** [comment]
yeah I should get that done

**Comment by snebjorn** [comment]
Separate health and sanity tokens for insanity/crippled/toughness are now available in the general token area.

**Comment by snebjorn** [comment]
I put an outline around the number in an attempt to solve exactly that issue. I'll have another look at it. I didn't really look at them from far away.

**Comment by snebjorn** [comment]
@metapone what does it look like on your screen? Cause this seems alright to me 
![image](https://user-images.githubusercontent.com/1266245/168640236-032757c1-1c18-4147-88dd-1f798a68f542.png)

**Comment by metapone** [comment]
Like this, because I like to see most of the board to get a better overview of the situation. Grant, the number is okay but not great at a glance, have to focus to get a better look because of the top part blending in with the white lines. ![20220516234628_1](https://user-images.githubusercontent.com/52821877/168643598-2720269d-857d-4eac-848c-f6ff5730fa7e.jpg)
