### ISSUE TITLE
Unclickable buttons in windowed fullscreen

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#6]
Specifically the buttons in the reserve: "Draw Debt" and "Restock". When I hover my mouse over it the cursor changes to a white arrow and the buttons are unclickable. I can temporarily mitigate this by opening the right click menu and closing it.

**Comment by snebjorn** [comment]
I can't reproduce this. I'm running windowed fullscreen myself and don't think I ever encountered this. Something else must be going on.
I tired switching the cursor mode, as that caused issues in the past, but didn't seem to make a difference.

**Comment by metapone** [comment]
I can't take a screenshot of it because when the white arrow cursor shows up F12 or Print Screen can't capture it, only when the normal "flower" blue cursor shows up that they can. I'll try to get a video of it later. If not possible, there's always the screen sharing option.

**Comment by metapone** [comment]
I can't reproduct it, so closing for now.

**Comment by metapone** [comment]
It happens again and I don't know why. I'll upload the TabletopPlayground.log file in a bit. If you need my saved state file or anything else, let me know.

**Comment by snebjorn** [comment]
I've adjusted some values. Hopefully it fixes it.
