### ISSUE TITLE
Missing Focus and Resource token

### ISSUE THREAD

**Issue by metapone** [snebjorn/ttp-eldritch-horror#8]
There are only 2 for each type in the game while it should be infinite.

**Comment by snebjorn** [comment]
Both the focus and ressource token stacks located in the general token area are "infinite stacks". Just like the others are.
You should be unable to split the 2 tokens apart, it should always create a new token when drawing from it.

**Comment by metapone** [comment]
😂
I think it's because I've just updated EH to your newest version (which happened even when the game said "Cannot connect to mod.io"), then immediately played. This is my first time using Focus and Resource token too. Anyhow, I've just restarted TTPG, created a new game and both token stacks work correctly so everything's fine.

**Comment by metapone** [comment]
Hey, this time not only the Focus and Resource tokens but the Impairment tokens also got turned into normal stacks! I crashed the game earlier and had to reload the Auto save, and last time I also have to reload a save due to splitting sessions, so maybe the problem lies in reloading an Auto save?

**Comment by snebjorn** [comment]
confirmed, fixing. Not sure how I missed that :/

**Comment by metapone** [comment]
Once again my Focus and Resource token stacks turn into normal 2-card stack, and again I was recovering from a TTPG crash and had to resort to Auto Save. With 2 occurence I'm now more certain that loading an Auto Save after a crash will broke certain infinite stacks.
